---
- hosts: all
  user: vagrant
  become: true
  tasks:
    - name: Install apt packages
      apt: 
        name: "{{ packages }}"
        state: present
        update_cache: yes
      vars:
        packages:
        - python3-dev 
        - libffi-dev 
        - gcc 
        - libssl-dev
        - python3-venv
    - name: Create directory
      file:
        path: /home/vagrant/openstack-env
        state: directory
    - name: Install ansible
      pip:
        name: ansible
        virtualenv: /home/vagrant/openstack-env
        virtualenv_command: /usr/bin/python3 -m venv
    - name: Install kolla-ansible
      pip:
        name: kolla-ansible
        virtualenv: /home/vagrant/openstack-env
    - name: Create directory
      become_method: sudo
      file:
        path: /etc/kolla
        state: directory
    - name: User right on kolla directory
      become_method: sudo
      shell: sudo chown vagrant:vagrant /etc/kolla
    - name: Copy globals.yml to /etc/kolla
      copy:
        src: globals.yml
        dest: /etc/kolla/globals.yml
    - name: Copy passwords.yml to /etc/kolla
      copy:
        src: /home/vagrant/openstack-env/share/kolla-ansible/etc_examples/kolla/passwords.yml
        dest: /etc/kolla/passwords.yml 
        remote_src: yes
    - name: User right on global.yml
      become_method: sudo
      shell: sudo chown vagrant:vagrant /etc/kolla/globals.yml
    - name: User right on passwords.yml
      become_method: sudo
      shell: sudo chown vagrant:vagrant /etc/kolla/passwords.yml
    - name: Copy the inventory files
      copy:
        src: /home/vagrant/openstack-env/share/kolla-ansible/ansible/inventory/all-in-one
        dest: /home/vagrant/all-in-one
        remote_src: yes        
    

